### ISSUE TITLE
Admin_logs messageUpdate DiscordAPIError : entity too large

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/Sil-Afian#13]
- [ ] Add attachment size for debug

```javascript
finishEmbed list error
 Message modifié 2022-10-10T17:19:42.072Z DiscordAPIError: Request entity too large
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ThreadChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async finishEmbed (file:///home/ewibot/ewibot/src/admin/utils.js:102:28)
    at async Client.onMessageUpdate (file:///home/ewibot/ewibot/src/admin/listeners.js:692:23) {
  method: 'post',
  path: '/channels/1012365101594058762/messages',
  code: 40005,
  httpStatus: 413,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: [Array],
      sticker_ids: undefined
    },
    files: [ [Object] ]
  }
}
```

**Comment by Eccleria** [comment]
```js
message reply error DiscordAPIError[40005]: Request entity too large
    at handleErrors (/home/ewibot/Sil-Afian/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/ewibot/Sil-Afian/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/ewibot/Sil-Afian/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/ewibot/Sil-Afian/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async ThreadChannel.send (/home/ewibot/Sil-Afian/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:195:15)
    at async messageReply (file:///home/ewibot/Sil-Afian/node_modules/ewilib/src/index.js:134:10)
    at async finishEmbed (file:///home/ewibot/Sil-Afian/src/admin/utils.js:114:26)
    at async Client.onMessageDelete (file:///home/ewibot/Sil-Afian/src/admin/listeners.js:624:23) {
  requestBody: {
    files: [ [Object] ],
    json: {
      content: '```Voici le.s pièce.s jointe.s du message principal loggé```',
      tts: false,
      nonce: undefined,
      enforce_nonce: false,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: [Object],
      attachments: [Array],
      sticker_ids: undefined,
      thread_name: undefined,
      applied_tags: undefined,
      poll: undefined
    }
  },
  rawError: { message: 'Request entity too large', code: 40005 },
  code: 40005,
  status: 413,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1012365101594058762/messages'
}
Uncaught exception: TypeError: Cannot read properties of undefined (reading 'client')
    at file:///home/ewibot/Sil-Afian/src/admin/listeners.js:641:22
    at Array.forEach (<anonymous>)
    at Client.onMessageDelete (file:///home/ewibot/Sil-Afian/src/admin/listeners.js:640:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
message Cannot read properties of undefined (reading 'client')
name TypeError
cause undefined
```
